USE [eProject3DB]
GO


CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDUser]  AS ('USER'+CONVERT([varchar](20),[Id])) PERSISTED NOT NULL,
	[UserNick] [nvarchar](20) NOT NULL,
	[UserPass] [nvarchar](20) NOT NULL,
	[Real_ID] [varchar](25) NULL,
	[Role] [nvarchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



